### PR TITLE
Room 4

### PR DESCRIPTION
**Pull request by nazim9919**
Adrieana and Mimi please revise the old system GUI and discuss the way to improve and change the system according to the Change Request that been approved. Thanks

### CODE REVIEW

**Comment by adsofia** [comment]
Cr 01 and CR02 are completed. I also attached the screenshots of the completed system for CR01 and CR02.
Picture1
Picture2

**Comment by mimiatikah** [comment]
CR 3 and CR 4 are comp
gmbr cr3
gmbr cr4

leted. here are the completed screenshots for C3 and C4

**Comment by nazim9919** [comment]
Thank adrieana and mimi for the update. Good job. Kudos

**Comment by nazim9919** [comment]
image
image
image
image

Files attached are the changes made for CR5 and CR6. if anyhting need to be alter please dont hesitate to inform me. Tq
image

**Comment by mimiatikah** [comment]
Good job my team!!!

**Comment by adsofia** [comment]
Thank you all for the good work! Good job!!

**Comment by nazim9919** [comment]
Excellent work team! now all of you are eligible to get 1 month bonus from Miss Sharaz as duit raya. tomorrow claim dont forget

**Comment by mimiatikah** [comment]
here are the new screenshots of the new version of CR7 and CR9.
cr folder
cr strtcture

**Comment by mimiatikah** [comment]
here are the new screenshots of the new version CR7 and CR8
cr folder
cr strtcture

**Comment by adsofia** [comment]
Here are the screenshot of the new version of CR09
Picture3

**Comment by nazim9919** [comment]
image
image
These are the last 2 CR that needed to be changed. Thank you for all the support and teamwork.

**Pull request closed without merging**
